spring:
  application:
    name: myApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://localhost:3306/myApplication?serverTimezone = GMT%2b8
    username: shuting
    password: 123456

server:
  port: 8801

mybatis:
  mapper-locations:classpath:mapper/*.xml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
